export const MATHS_PREMIUM = {
    "Logarithms": [
        { q: "Evaluate the value of $\\log_{10} 1$.", a: "$0$", o: ["$1$", "$10$", "Not defined"], d: "Easy" },
        { q: "If $a^x = b$, then which of the following logarithmic relations is true?", a: "$\\log_a b = x$", o: ["$\\log_b a = x$", "$\\log_x a = b$", "$\\log_a x = b$"], d: "Easy" },
        { q: "The value of $\\log_e e$ (natural logarithm of $e$) is:", a: "$1$", o: ["$0$", "$e$", "$10$"], d: "Easy" },
        { q: "Express $2^5 = 32$ in logarithmic form.", a: "$\\log_2 32 = 5$", o: ["$\\log_5 32 = 2$", "$\\log_{32} 5 = 2$", "$\\log_2 5 = 32$"], d: "Easy" },
        { q: "Find the value of $\\log_3 81$.", a: "$4$", o: ["$3$", "$9$", "$27$"], d: "Medium" },
        { q: "Determine the value of $\\log_{10} 0.01$.", a: "$-2$", o: ["$-1$", "$0$", "$2$"], d: "Medium" },
        { q: "Solve for $x$: $\\log_x 64 = 3$.", a: "$4$", o: ["$8$", "$2$", "$6$"], d: "Medium" },
        { q: "Using the change of base formula, $\\log_a b$ is equal to:", a: "$\\frac{\\log_c b}{\\log_c a}$", o: ["$\\log_c b - \\log_c a$", "$\\log_c b \\cdot \\log_c a$", "$\\frac{\\log_c a}{\\log_c b}$"], d: "Medium" },
        { q: "If $\\log 2 = 0.3010$ and $\\log 3 = 0.4771$, find the value of $\\log 6$.", a: "$0.7781$", o: ["$0.1761$", "$1.4313$", "$0.8451$"], d: "Hard" },
        { q: "Evaluate $\\log_2 (\\log_3 81)$.", a: "$2$", o: ["$1$", "$4$", "$0$"], d: "Hard" },
        { q: "The value of $\\log_{10} 1000$ is:", a: "$3$", o: ["$2$", "$4$", "$10$"], d: "Easy" },
        { q: "Which property is correct for $\\log(mn)$?", a: "$\\log m + \\log n$", o: ["$\\log m - \\log n$", "$\\log m \\cdot \\log n$", "$\\log m / \\log n$"], d: "Easy" },
        { q: "Calculate $\\log_5 125$.", a: "$3$", o: ["$2$", "$4$", "$5$"], d: "Medium" },
        { q: "If $\\log_{10} x = -3$, then $x$ is:", a: "$0.001$", o: ["$1000$", "$0.01$", "$0.0001$"], d: "Medium" },
        { q: "Solve for $x$: $2 \\log x = \\log 16$.", a: "$4$", o: ["$2$", "$8$", "$16$"], d: "Hard" }
    ],
    "Matrices": [
        { q: "A matrix with an equal number of rows and columns is known as a:", a: "Square matrix", o: ["Identity matrix", "Diagonal matrix", "Scalar matrix"], d: "Easy" },
        { q: "The trace of a square matrix is the sum of its:", a: "Principal diagonal elements", o: ["All elements", "Off-diagonal elements", "First row elements"], d: "Easy" },
        { q: "A square matrix $A$ is singular if its determinant $|A|$ is:", a: "$0$", o: ["$1$", "$-1$", "Greater than $0$"], d: "Easy" },
        { q: "If $A$ is a $3 \\times 2$ matrix and $B$ is a $2 \\times 3$ matrix, what is the order of $AB$?", a: "$3 \\times 3$", o: ["$2 \\times 2$", "$3 \\times 2$", "$2 \\times 3$"], d: "Medium" },
        { q: "An identity matrix $I$ is a diagonal matrix where all diagonal elements are equal to:", a: "$1$", o: ["$0$", "Any constant", "The trace"], d: "Medium" },
        { q: "If $A$ is a symmetric matrix, then $A^T$ (transpose of $A$) is equal to:", a: "$A$", o: ["$-A$", "$I$", "$A^{-1}$"], d: "Medium" },
        { q: "The inverse of a matrix $A$ exists if and only if:", a: "$|A| \\neq 0$", o: ["$|A| = 0$", "$A$ is square", "$A$ is identity"], d: "Medium" },
        { q: "For any two matrices $A$ and $B$, the property $(AB)^T$ is equal to:", a: "$B^T A^T$", o: ["$A^T B^T$", "$AB$", "$BA$"], d: "Hard" },
        { q: "The value of the determinant $\\begin{vmatrix} 1 & 2 \\\\ 3 & 4 \\end{vmatrix}$ is:", a: "$-2$", o: ["$2$", "$10$", "$-10$"], d: "Hard" },
        { q: "If $A^2 = A$, then the matrix $A$ is called:", a: "Idempotent", o: ["Nilpotent", "Involuntary", "Orthogonal"], d: "Hard" },
        { q: "A matrix whose all elements are zero is called:", a: "Null matrix", o: ["Identity matrix", "Scalar matrix", "Unit matrix"], d: "Easy" },
        { q: "The order of a matrix with $m$ rows and $n$ columns is:", a: "$m \\times n$", o: ["$n \\times m$", "$m + n$", "$m - n$"], d: "Easy" },
        { q: "Find the adjoint of $\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}$.", a: "$\\begin{pmatrix} d & -b \\\\ -c & a \\end{pmatrix}$", o: ["$\\begin{pmatrix} a & c \\\\ b & d \\end{pmatrix}$", "$\\begin{pmatrix} d & b \\\\ c & a \\end{pmatrix}$", "$\\begin{pmatrix} -d & b \\\\ c & -a \\end{pmatrix}$"], d: "Hard" },
        { q: "If $A$ is an orthogonal matrix, then $|A|$ is equal to:", a: "$\\pm 1$", o: ["$0$", "$2$", "$\pm 2$"], d: "Hard" }
    ],
    "Trigonometry": [
        { q: "The value of $\\sin^2 \\theta + \\cos^2 \\theta$ is always equal to:", a: "$1$", o: ["$0$", "$-1$", "$2$"], d: "Easy" },
        { q: "The value of $\\tan 45^\\circ$ is:", a: "$1$", o: ["$0$", "$\\frac{1}{\\sqrt{2}}$", "$\\sqrt{3}$"], d: "Easy" },
        { q: "Which of the following describes the relationship $\\sec^2 \\theta$?", a: "$1 + \\tan^2 \\theta$", o: ["$1 - \\tan^2 \\theta$", "$1 + \\sin^2 \\theta$", "$1 + \\cos^2 \\theta$"], d: "Easy" },
        { q: "Find the value of $\\cos 60^\\circ$.", a: "$0.5$", o: ["$0.866$", "$1$", "$0$"], d: "Easy" },
        { q: "The period of the function $f(x) = \\sin x$ is:", a: "$2\\pi$", o: ["$\\pi$", "$\\pi/2$", "$4\\pi$"], d: "Medium" },
        { q: "Express $\\tan \\theta$ in terms of $\\sin \\theta$ and $\\cos \\theta$.", a: "$\\frac{\\sin \\theta}{\\cos \\theta}$", o: ["$\\frac{\\cos \\theta}{\\sin \\theta}$", "$\\sin \\theta \\cdot \\cos \\theta$", "$\\sin^2 \\theta$"], d: "Medium" },
        { q: "The value of $\\sin(90^\\circ - \\theta)$ is equal to:", a: "$\\cos \\theta$", o: ["$-\\cos \\theta$", "$\\sin \\theta$", "$\\tan \\theta$"], d: "Medium" },
        { q: "Evaluate $\\sin \\frac{\\pi}{3} \\cos \\frac{\\pi}{6} + \\cos \\frac{\\pi}{3} \\sin \\frac{\\pi}{6}$.", a: "$1$", o: ["$0$", "$0.5$", "$\\frac{\\sqrt{3}}{2}$"], d: "Hard" },
        { q: "If $\\tan \\theta = \\frac{3}{4}$ and $\\theta$ is in the first quadrant, find $\\sec \\theta$.", a: "$\\frac{5}{4}$", o: ["$\\frac{4}{5}$", "$\\frac{5}{3}$", "$\\frac{3}{5}$"], d: "Hard" },
        { q: "The general solution of $\\sin \\theta = 0$ is:", a: "$n\\pi$", o: ["$2n\\pi$", "$(2n+1)\\pi/2$", "$n\\pi/2$"], d: "Hard" },
        { q: "The value of $\\cos 0^\\circ$ is:", a: "$1$", o: ["$0$", "$-1$", "Not defined"], d: "Easy" },
        { q: "What is $\\sec \\theta$ equal to?", a: "$1/\\cos \\theta$", o: ["$1/\\sin \\theta$", "$1/\\tan \\theta$", "$\\sin \\theta$"], d: "Easy" },
        { q: "Evaluate $\\sin 30^\\circ + \\cos 60^\\circ$.", a: "$1$", o: ["$0$", "$0.5$", "$\\sqrt{3}$"], d: "Medium" },
        { q: "If $\\theta = 30^\\circ$, then $\\tan 2\\theta$ is:", a: "$\\sqrt{3}$", o: ["$1/\\sqrt{3}$", "$1$", "$0$"], d: "Medium" },
        { q: "The value of $\\sin^{-1}(\\sin \\frac{\\pi}{2})$ is:", a: "$\\pi/2$", o: ["$0$", "$\\pi$", "$1$"], d: "Hard" }
    ],
    "Differentiation": [
        { q: "The derivative of $x^n$ with respect to $x$ is:", a: "$nx^{n-1}$", o: ["$x^{n+1}/(n+1)$", "$nx^n$", "$n^x$"], d: "Easy" },
        { q: "The derivative of a constant $c$ is:", a: "$0$", o: ["$1$", "$c$", "Does not exist"], d: "Easy" },
        { q: "Find $\\frac{d}{dx}(\\sin x)$.", a: "$\\cos x$", o: ["$-\\cos x$", "$\\sec^2 x$", "$\\tan x$"], d: "Easy" },
        { q: "The derivative of $e^x$ with respect to $x$ is:", a: "$e^x$", o: ["$xe^{x-1}$", "$\\ln x$", "$e$"], d: "Medium" },
        { q: "Using the product rule, $\\frac{d}{dx}(uv)$ is:", a: "$u v' + v u'$", o: ["$u v' - v u'$", "$u' v'$", "$u/v'$"], d: "Medium" },
        { q: "The derivative of $\\ln x$ is:", a: "$1/x$", o: ["$e^x$", "$x$", "$-1/x^2$"], d: "Medium" },
        { q: "Find the derivative of $\\tan x$.", a: "$\\sec^2 x$", o: ["$-\\sec^2 x$", "$\\cos^2 x$", "$\\sin x$"], d: "Medium" },
        { q: "Evaluate the derivative of $\\sin(x^2)$.", a: "$2x \\cos(x^2)$", o: ["$\\cos(x^2)$", "$2x \\sin(x^2)$", "$-2x \\cos(x^2)$"], d: "Hard" },
        { q: "What is the second derivative of $x^3 + 2x^2 + 5$?", a: "$6x + 4$", o: ["$3x^2 + 4x$", "$6x$", "$3x + 2$"], d: "Hard" },
        { q: "The slope of the tangent to the curve $y = f(x)$ at $x = a$ is given by:", a: "$f'(a)$", o: ["$f(a)$", "$a$", "$0$"], d: "Hard" },
        { q: "Find $\\frac{d}{dx}(\\cos x)$.", a: "$-\\sin x$", o: ["$\\sin x$", "$\\sec^2 x$", "$0$"], d: "Easy" },
        { q: "The derivative of $\\tan^{-1} x$ is:", a: "$1/(1+x^2)$", o: ["$1/\\sqrt{1-x^2}$", "$1/(1-x^2)$", "$x^2$"], d: "Medium" },
        { q: "Differentiate $y = \sqrt{x}$.", a: "$1/(2\\sqrt{x})$", o: ["$2\\sqrt{x}$", "$1/x$", "$x^{1/2}$"], d: "Medium" },
        { q: "Find $\\frac{d}{dx}(\\log_a x)$.", a: "$1/(x \\ln a)$", o: ["$1/x$", "$a^x$", "$\\ln a / x$"], d: "Hard" }
    ],
    "Integration": [
        { q: "The integral $\\int x^n dx$ (for $n \\neq -1$) is:", a: "$\\frac{x^{n+1}}{n+1} + C$", o: ["$nx^{n-1} + C$", "$x^n + C$", "$\\frac{x^n}{n} + C$"], d: "Easy" },
        { q: "Evaluate $\\int \\cos x dx$.", a: "$\\sin x + C$", o: ["$-\\sin x + C$", "$\\tan x + C$", "$\\sin^2 x + C$"], d: "Easy" },
        { q: "The integral $\\int \\frac{1}{x} dx$ is:", a: "$\\ln |x| + C$", o: ["$x + C$", "$-1/x^2 + C$", "$e^x + C$"], d: "Easy" },
        { q: "What is the value of $\\int e^x dx$?", a: "$e^x + C$", o: ["$xe^x + C$", "$\\ln x + C$", "$e^{x+1} + C$"], d: "Easy" },
        { q: "Evaluate the definite integral $\\int_0^1 x dx$.", a: "$0.5$", o: ["$1$", "$0$", "$2$"], d: "Medium" },
        { q: "The integral $\\int \\sec^2 x dx$ results in:", a: "$\\tan x + C$", o: ["$\\sec x + C$", "$\\cos x + C$", "$-\\tan x + C$"], d: "Medium" },
        { q: "Integration is the reverse process of:", a: "Differentiation", o: ["Multiplication", "Addition", "Logarithm"], d: "Medium" },
        { q: "Evaluate $\\int \\sin(2x) dx$.", a: "$-\\frac{1}{2} \\cos(2x) + C$", o: ["$\\frac{1}{2} \\cos(2x) + C$", "$-2 \\cos(2x) + C$", "$\\cos(2x) + C$"], d: "Hard" },
        { q: "Find $\\int_1^2 x^2 dx$.", a: "$7/3$", o: ["$3$", "$1$", "$8/3$"], d: "Hard" },
        { q: "The area under the curve $y = f(x)$ from $x=a$ to $x=b$ is given by:", a: "$\\int_a^b f(x) dx$", o: ["$f(b) - f(a)$", "$f'(b) - f'(a)$", "$\\int f(x) dx$"], d: "Hard" },
        { q: "Evaluate $\\int 0 dx$.", a: "$C$", o: ["$0$", "$x$", "$1$"], d: "Easy" },
        { q: "What is $\\int \\sin x dx$?", a: "$-\\cos x + C$", o: ["$\\cos x + C$", "$0$", "$\\tan x + C$"], d: "Easy" },
        { q: "Find $\\int (2x + 3) dx$.", a: "$x^2 + 3x + C$", o: ["$2x^2 + 3x + C$", "$x^2 + C$", "$2 + C$"], d: "Medium" },
        { q: "Evaluate $\\int e^{3x} dx$.", a: "$\\frac{1}{3} e^{3x} + C$", o: ["$3e^{3x} + C$", "$e^{3x} + C$", "$e^x + C$"], d: "Medium" },
        { q: "The value of $\\int \\sec x \\tan x dx$ is:", a: "$\\sec x + C$", o: ["$\\tan x + C$", "$\\cos x + C$", "$\\sin x + C$"], d: "Hard" }
    ]
};

export const PHYSICS_PREMIUM = {
    "Units & Measurements": [
        { q: "The SI unit of luminous intensity is:", a: "candela", o: ["mole", "kelvin", "ampere"], d: "Easy" },
        { q: "Which of the following is NOT a fundamental physical quantity?", a: "Force", o: ["Mass", "Time", "Length"], d: "Easy" },
        { q: "One light year is a unit of:", a: "Distance", o: ["Time", "Speed", "Intensity"], d: "Easy" },
        { q: "The dimensional formula for Force is:", a: "$[MLT^{-2}]$", o: ["$[ML^2T^{-2}]$", "$[MLT^{-1}]$", "$[M^2LT^{-2}]$"], d: "Medium" },
        { q: "The number of significant figures in $0.007$ is:", a: "$1$", o: ["$3$", "$4$", "$2$"], d: "Medium" },
        { q: "Parsec is the unit of:", a: "Astronomical distance", o: ["Time", "Mass", "Angle"], d: "Medium" },
        { q: "The SI unit of solid angle is:", a: "steradian", o: ["radian", "degree", "candela"], d: "Medium" },
        { q: "What is the dimensional formula of universal gravitational constant $G$?", a: "$[M^{-1}L^3T^{-2}]$", o: ["$[ML^3T^{-2}]$", "$[M^{-1}L^2T^{-2}]$", "$[ML^2T^{-1}]$"], d: "Hard" },
        { q: "The density of a material in CGS system is $4 \\text{ g/cm}^3$. In a system where unit of length is $10 \\text{ cm}$ and unit of mass is $100 \\text{ g}$, the density will be:", a: "$40$", o: ["$4$", "$0.4$", "$400$"], d: "Hard" },
        { q: "The dimensional formula for pressure is:", a: "$[ML^{-1}T^{-2}]$", o: ["$[MLT^{-2}]$", "$[ML^2T^{-2}]$", "$[ML^{-2}T^{-2}]$"], d: "Hard" },
        { q: "Which of the following is a unitless quantity?", a: "Strain", o: ["Stress", "Force", "Pressure"], d: "Easy" },
        { q: "What is the SI unit of work?", a: "Joule", o: ["Newton", "Watt", "Pascal"], d: "Easy" },
        { q: "The number of base units in SI system is:", a: "$7$", o: ["$5$", "$9$", "$3$"], d: "Easy" },
        { q: "One micron is equal to:", a: "$10^{-6} \\text{ m}$", o: ["$10^{-9} \\text{ m}$", "$10^{-3} \\text{ m}$", "$10^{-12} \\text{ m}$"], d: "Medium" },
        { q: "The dimensional formula of surface tension is:", a: "$[MT^{-2}]$", o: ["$[MLT^{-2}]$", "$[ML^{-1}T^{-2}]$", "$[ML^2T^{-2}]$"], d: "Medium" },
        { q: "Dimensional formula for kinetic energy is:", a: "$[ML^2T^{-2}]$", o: ["$[MLT^{-2}]$", "$[ML^2T^{-1}]$", "$[MLT^{-1}]$"], d: "Hard" }
    ],
    "Force & Motion": [
        { q: "Newton's first law of motion provides a qualitative definition of:", a: "Inertia", o: ["Force", "Momentum", "Acceleration"], d: "Easy" },
        { q: "The rate of change of linear momentum is proportional to:", a: "Applied force", o: ["Velocity", "Acceleration", "Displacement"], d: "Easy" },
        { q: "A body is in equilibrium when the net force acting on it is:", a: "$Zero$", o: ["Constant", "Maximum", "Infinite"], d: "Easy" },
        { q: "The friction that exists between surfaces when one body just tends to slide over another is:", a: "Limiting friction", o: ["Static friction", "Kinetic friction", "Rolling friction"], d: "Medium" },
        { q: "The coefficient of static friction is usually:", a: "Greater than kinetic friction", o: ["Less than kinetic friction", "Equal to kinetic friction", "Zero"], d: "Medium" },
        { q: "Centripetal force is always directed towards the:", a: "Center of circular path", o: ["Tangent to the path", "Away from the center", "Any direction"], d: "Medium" },
        { q: "A passenger in a moving bus is thrown forward when the bus stops suddenly. This is due to:", a: "Inertia of motion", o: ["Inertia of rest", "Inertia of direction", "Momentum"], d: "Medium" },
        { q: "Two bodies of masses $1 \\text{ kg}$ and $4 \\text{ kg}$ have equal kinetic energies. The ratio of their linear momenta is:", a: "$1:2$", o: ["$1:4$", "$2:1$", "$4:1$"], d: "Hard" },
        { q: "If the force acting on a body is doubled and its mass is halved, the acceleration becomes:", a: "$4 \\text{ times}$", o: ["Half", "Double", "Remains same"], d: "Hard" },
        { q: "The minimum velocity required for an object to escape Earth's gravity is:", a: "$11.2 \\text{ km/s}$", o: ["$8.0 \\text{ km/s}$", "$11.2 \\text{ m/s}$", "$9.8 \\text{ km/s}$"], d: "Hard" },
        { q: "Acceleration due to gravity $g$ at the center of the earth is:", a: "$0$", o: ["$9.8 \\text{ m/s}^2$", "Infinite", "Same as surface"], d: "Easy" },
        { q: "Momentum is a product of mass and:", a: "Velocity", o: ["Speed", "Acceleration", "Force"], d: "Easy" },
        { q: "The path of a projectile is called:", a: "Trajectory", o: ["Orbit", "Parabola", "Circle"], d: "Easy" },
        { q: "When a body moves with constant velocity, its acceleration is:", a: "$0$", o: ["Constant", "Variable", "Maximum"], d: "Medium" },
        { q: "The range of a projectile is maximum when the angle of projection is:", a: "$45^\\circ$", o: ["$30^\\circ$", "$60^\\circ$", "$90^\\circ$"], d: "Medium" },
        { q: "A body of mass $m$ moves in a circle of radius $r$ with velocity $v$. The centripetal force is:", a: "$mv^2/r$", o: ["$m v/r$", "$m r/v^2$", "$v^2/mr$"], d: "Hard" },
        { q: "Impulse is equal to change in:", a: "Momentum", o: ["Force", "Velocity", "Acceleration"], d: "Medium" },
        { q: "The work done by a centripetal force is always:", a: "$0$", o: ["Positive", "Negative", "Infinite"], d: "Hard" }
    ],
    "Viscosity": [
        { q: "The property of a fluid by which it opposes relative motion between its layers is:", a: "Viscosity", o: ["Surface tension", "Capillarity", "Elasticity"], d: "Easy" },
        { q: "The SI unit of coefficient of viscosity is:", a: "Pa $\\cdot$ s (Pascal-second)", o: ["Poise", "Newton/meter", "Pascal"], d: "Easy" },
        { q: "Terminal velocity of a sphere falling through a viscous medium depends on the square of its:", a: "Radius", o: ["Mass", "Density", "Velocity"], d: "Easy" },
        { q: "With an increase in temperature, the viscosity of a liquid:", a: "Decreases", o: ["Increases", "Remains same", "Fluctuates"], d: "Medium" },
        { q: "Stokes' law relates viscous force to the:", a: "Velocity of the body", o: ["Pressure of fluid", "Density of body", "Volume of fluid"], d: "Medium" },
        { q: "Reynolds number is used to determine the:", a: "Type of fluid flow", o: ["Viscosity of fluid", "Surface tension", "Density of fluid"], d: "Medium" },
        { q: "For a streamline flow, the velocity of every particle at a given point:", a: "Remains constant over time", o: ["Increases with time", "Decreases with time", "Changes direction"], d: "Medium" },
        { q: "Poiseuille’s formula relates the rate of flow of a liquid through a capillary tube to the:", a: "Pressure difference", o: ["Surface tension", "Density", "Gravity"], d: "Hard" },
        { q: "The viscosity of gases ________ with an increase in temperature.", a: "Increases", o: ["Decreases", "Remains constant", "First increases then decreases"], d: "Hard" },
        { q: "A small metal ball of radius $r$ falls through a viscous liquid with terminal velocity $v$. If another ball of radius $2r$ is dropped in the same liquid, its terminal velocity will be:", a: "$4v$", o: ["$2v$", "$v/2$", "$8v$"], d: "Hard" },
        { q: "Ideal fluids are assumed to have zero:", a: "Viscosity", o: ["Density", "Volume", "Mass"], d: "Easy" },
        { q: "The flow becomes turbulent when Reynolds number exceeds:", a: "$2000$", o: ["$100$", "$500$", "$10$"], d: "Easy" },
        { q: "Viscosity is also known as:", a: "Internal friction", o: ["Surface energy", "Static friction", "Cohesion"], d: "Easy" },
        { q: "Blood flow in arteries is generally:", a: "Streamline", o: ["Turbulent", "Viscous", "Elastic"], d: "Medium" },
        { q: "The dimension of coefficient of viscosity is:", a: "$[ML^{-1}T^{-1}]$", o: ["$[MLT^{-1}]$", "$[ML^{-1}T^{-2}]$", "$[M^0L^0T^0]$"], d: "Medium" },
        { q: "Viscosity of water is ________ than that of honey.", a: "Lower", o: ["Higher", "Same", "Zero"], d: "Hard" }
    ],
    "Elasticity": [
        { q: "Hooke's law states that within the elastic limit, stress is proportional to:", a: "Strain", o: ["Young's modulus", "Area", "Force"], d: "Easy" },
        { q: "The SI unit of stress is:", a: "$N/m^2$ or Pascal", o: ["Newton", "Joule", "Watt"], d: "Easy" },
        { q: "Young's modulus is define as the ratio of Longitudinal stress to:", a: "Longitudinal strain", o: ["Volume strain", "Shear strain", "Bulk strain"], d: "Easy" },
        { q: "A material that does not return to its original shape after removing the deforming force is:", a: "Plastic", o: ["Elastic", "Brittle", "Ductile"], d: "Medium" },
        { q: "The ratio of lateral strain to longitudinal strain is called:", a: "Poisson's ratio", o: ["Young's modulus", "Bulk modulus", "Rigidity modulus"], d: "Medium" },
        { q: "The dimensional formula for strain is:", a: "Dimensionless ($[M^0L^0T^0]$)", o: ["$[L^1]$", "$[ML^{-1}T^{-2}]$", "$[LT^{-1}]$"], d: "Medium" },
        { q: "What is the relation between Young’s modulus ($Y$), Bulk modulus ($K$) and Modulus of rigidity ($\\eta$)?", a: "$9/Y = 3/\\eta + 1/K$", o: ["$Y = 3K(1-2\\sigma)$", "$9Y = 3/\\eta + 1/K$", "$Y = 2\\eta(1+\\sigma)$"], d: "Hard" },
        { q: "Steel is more elastic than rubber because it requires ________ stress for same strain.", a: "More", o: ["Less", "Same", "Zero"], d: "Medium" },
        { q: "The maximum stress a material can withstand is the:", a: "Breaking stress", o: ["Elastic limit", "Yield point", "Strain"], d: "Medium" },
        { q: "Bulk modulus is applicable for:", a: "Solids, Liquids, and Gases", o: ["Solids only", "Gases only", "Liquids only"], d: "Hard" },
        { q: "The reciprocal of Bulk modulus is called:", a: "Compressibility", o: ["Rigidity", "Elasticity", "Viscosity"], d: "Easy" },
        { q: "Which of the following has highest elasticity?", a: "Steel", o: ["Copper", "Rubber", "Aluminum"], d: "Easy" },
        { q: "Strain has units of:", a: "No units", o: ["Meter", "Pascal", "Newton"], d: "Easy" },
        { q: "For a perfectly rigid body, Young's modulus is:", a: "Infinite", o: ["Zero", "$1$", "Small"], d: "Medium" },
        { q: "Work done in stretching a wire is proportional to:", a: "Square of change in length", o: ["Change in length", "Length", "Area"], d: "Hard" }
    ],
    "Surface Tension": [
        { q: "The force per unit length acting on the surface of a liquid is called:", a: "Surface tension", o: ["Surface energy", "Viscosity", "Cohesive force"], d: "Easy" },
        { q: "Small droplets of liquid take spherical shape due to:", a: "Surface tension", o: ["Gravity", "Viscosity", "Atmospheric pressure"], d: "Easy" },
        { q: "The SI unit of surface tension is:", a: "$N/m$", o: ["$N/m^2$", "$J/m$", "$Pa$"], d: "Easy" },
        { q: "With an increase in temperature, the surface tension of a liquid usually:", a: "Decreases", o: ["Increases", "Remains same", "Becomes zero"], d: "Medium" },
        { q: "The rise of liquid in a capillary tube is due to:", a: "Capillarity", o: ["Gravity", "Inertia", "Viscosity"], d: "Medium" },
        { q: "The angle of contact for pure water and clean glass is:", a: "$0^\\circ$", o: ["$90^\\circ$", "$135^\\circ$", "$8^\\circ$"], d: "Medium" },
        { q: "The excess pressure inside a soap bubble of radius $r$ is:", a: "$4T/r$", o: ["$2T/r$", "$T/r$", "$8T/r$"], d: "Hard" },
        { q: "Detergents reduce the ________ of water.", a: "Surface tension", o: ["Viscosity", "Density", "Purity"], d: "Easy" },
        { q: "Energy stored in the surface of a liquid is:", a: "Surface energy", o: ["Potential energy", "Kinetic energy", "Thermal energy"], d: "Medium" },
        { q: "A pin floats on water due to:", a: "Surface tension", o: ["Buoyancy", "Viscosity", "Density"], d: "Easy" },
        { q: "Angle of contact for mercury with glass is:", a: "Obtuse", o: ["Acute", "Right angle", "$0^\\circ$"], d: "Medium" },
        { q: "If the radius of a capillary tube is halved, the height of liquid rise will:", a: "Double", o: ["Halve", "Remains same", "Become four times"], d: "Medium" },
        { q: "Cohesive force is strongest between molecules of:", a: "Same substance", o: ["Different substances", "Water and glass", "Solid and liquid"], d: "Hard" },
        { q: "Surface tension of a liquid is zero at its:", a: "Critical temperature", o: ["Boiling point", "Freezing point", "$0^\\circ$C"], d: "Hard" },
        { q: "Work done in blowing a bubble of radius $R$ is ($T$ = surface tension):", a: "$8\\pi R^2 T$", o: ["$4\\pi R^2 T$", "$2\\pi R^2 T$", "$\\pi R^2 T$"], d: "Hard" }
    ]
};
